blueprint:
  name: Reset MA
  description: "Hardcoded reset for MA + radio index. No inputs."
  domain: script

mode: single

sequence:
  - alias: Clear Music Assistant Playlist
    action: media_player.clear_playlist
    target:
      entity_id: media_player.speakers_ma

  - alias: Turn Off Music Assistant
    action: media_player.turn_off
    target:
      entity_id: media_player.speakers_ma

  - alias: Reset Radio Station Index
    action: input_number.set_value
    target:
      entity_id: input_number.radio_station_index
    data:
      value: -1
