blueprint:
  name: Room - Power off
  description: |
    Hardcoded script blueprint for "power_off".
  domain: script

mode: single
max_exceeded: silent

sequence:
  - variables:
      _tv_was_on: "{{ is_state('binary_sensor.tv', 'on') }}"
  - action: input_select.select_option
    data:
      option: power_off
    target:
      entity_id: input_select.activity
  - parallel:
      - action: media_player.turn_off
        target:
          entity_id: media_player.speakers
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ _tv_was_on }}"
            sequence:
              - event: pihub.cmd
                event_data:
                  dest: pi
                  text: macro
                  name: power_off
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ _tv_was_on }}"
        sequence:
          - alias: Wait for TV = off (max 7s)
            wait_template: "{{ states('binary_sensor.tv') != 'on' }}"
            timeout: "00:00:07"
            continue_on_timeout: true
          - delay: "00:00:01"
  - action: script.reset_ma
  - action: input_select.select_option
    data:
      option: power_off
    target:
      entity_id: input_select.last_run_activity
